name: CD

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/cd.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    uses: ArkeonProject/organization-tools/.github/workflows/cd-node-vercel.yml@v1.1.5
    with:
      node-version: '20'
      package-manager: 'pnpm'
    secrets: inherit
